"""
Generated By: Claude Code (Claude Sonnet 4.5)

Configuration for master calibration frame organization.

Defines metadata properties used for organizing and naming master calibration frames.
Uses normalized keyword names from ap-common normalization.
"""

# Import constants from ap-common
from ap_common.constants import (
    NORMALIZED_HEADER_TYPE,
    NORMALIZED_HEADER_CAMERA,
    NORMALIZED_HEADER_GAIN,
    NORMALIZED_HEADER_OFFSET,
    NORMALIZED_HEADER_SETTEMP,
    NORMALIZED_HEADER_READOUTMODE,
    NORMALIZED_HEADER_EXPOSURESECONDS,
    NORMALIZED_HEADER_DATE,
    NORMALIZED_HEADER_FILTER,
    NORMALIZED_HEADER_FOCALLEN,
    NORMALIZED_HEADER_OPTIC,
    TYPE_MASTER_BIAS,
    TYPE_MASTER_DARK,
    TYPE_MASTER_FLAT,
    MASTER_CALIBRATION_TYPES,
)

# Required metadata properties for each frame type
# These are used to validate that files can be properly organized
REQUIRED_PROPERTIES = {
    TYPE_MASTER_BIAS: [
        NORMALIZED_HEADER_CAMERA,  # Required for directory structure
    ],
    TYPE_MASTER_DARK: [
        NORMALIZED_HEADER_CAMERA,  # Required for directory structure
    ],
    TYPE_MASTER_FLAT: [
        NORMALIZED_HEADER_CAMERA,  # Required for directory structure
        NORMALIZED_HEADER_DATE,  # Required for date subdirectory
    ],
}

# Metadata properties included in filenames for each frame type
# Order matters - properties appear in filename in this order
FILENAME_PROPERTIES = {
    TYPE_MASTER_BIAS: [
        NORMALIZED_HEADER_GAIN,
        NORMALIZED_HEADER_OFFSET,
        NORMALIZED_HEADER_SETTEMP,
        NORMALIZED_HEADER_READOUTMODE,
    ],
    TYPE_MASTER_DARK: [
        NORMALIZED_HEADER_EXPOSURESECONDS,  # Must be first for dark frames
        NORMALIZED_HEADER_GAIN,
        NORMALIZED_HEADER_OFFSET,
        NORMALIZED_HEADER_SETTEMP,
        NORMALIZED_HEADER_READOUTMODE,
    ],
    TYPE_MASTER_FLAT: [
        NORMALIZED_HEADER_FILTER,
        NORMALIZED_HEADER_GAIN,
        NORMALIZED_HEADER_OFFSET,
        NORMALIZED_HEADER_SETTEMP,
        NORMALIZED_HEADER_FOCALLEN,
        NORMALIZED_HEADER_READOUTMODE,
    ],
}

# Optional metadata properties
# These are used if present but do not cause failures if missing
OPTIONAL_PROPERTIES = {
    TYPE_MASTER_FLAT: [
        NORMALIZED_HEADER_OPTIC,  # Optional optic subdirectory for flats
    ],
}
